@baseUrl = http://localhost:3000

### Login
# @name userLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "normal@test.com",
  "password": "123456"
}

###

@authToken = {{userLogin.response.body.access_token}}

### Protected
# @name getUsers
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}